title: Your Name
description: Builder. Writer. Thinker.
url: https://capatric.github.io
baseurl: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Collections
collections:
  writing:
    output: true
    permalink: /writing/:title/
  projects:
    output: true
    permalink: /projects/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "writing"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

# Exclude from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
