# Site settings
title: Carlos Patricio
email: carangpatmar@gmail.com
description: Electronics Engineer
url: "https://capatric.github.io"
github_username: capatric
linkedin_username: capatric
baseurl: ""

# Build settings
markdown: kramdown
permalink: /posts/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Navigation
navigation:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Posts
    url: /posts
